/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2025.1.0.2506031608
    Soft IP Version: 1.0.0
    2025 09 02 08:13:57
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module uart (ahbl_haddr_i, ahbl_hburst_i, ahbl_hrdata_o, ahbl_hsize_i,
    ahbl_htrans_i, ahbl_hwdata_i, ahbl_hready_i, ahbl_hreadyout_o,
    ahbl_hresp_o, ahbl_hsel_i, ahbl_hwrite_i, i_rxd, o_txd, int_o, systime_i,
    clk, resetn)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  [31:0]  ahbl_haddr_i;
    input  [2:0]  ahbl_hburst_i;
    output  [31:0]  ahbl_hrdata_o;
    input  [2:0]  ahbl_hsize_i;
    input  [1:0]  ahbl_htrans_i;
    input  [31:0]  ahbl_hwdata_i;
    input  ahbl_hready_i;
    output  ahbl_hreadyout_o;
    output  ahbl_hresp_o;
    input  ahbl_hsel_i;
    input  ahbl_hwrite_i;
    input  i_rxd;
    output  o_txd;
    output  int_o;
    input  [31:0]  systime_i;
    input  clk;
    input  resetn;
endmodule