/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2025.1.0.2506031608
    Soft IP Version: 1.0.0
    2025 08 21 07:25:19
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module gpio (gpio_io, gpo_o, gpi_o, int_o, ahbl_haddr_i, ahbl_hburst_i,
    ahbl_hrdata_o, ahbl_hsize_i, ahbl_htrans_i, ahbl_hwdata_i, ahbl_hready_i,
    ahbl_hreadyout_o, ahbl_hresp_o, ahbl_hsel_i, ahbl_hwrite_i, clk_i,
    resetn_i)/* synthesis syn_black_box syn_declare_black_box=1 */;
    inout  [7:0]  gpio_io;
    output  [7:0]  gpo_o;
    output  [7:0]  gpi_o;
    output  int_o;
    input  [31:0]  ahbl_haddr_i;
    input  [2:0]  ahbl_hburst_i;
    output  [31:0]  ahbl_hrdata_o;
    input  [2:0]  ahbl_hsize_i;
    input  [1:0]  ahbl_htrans_i;
    input  [31:0]  ahbl_hwdata_i;
    input  ahbl_hready_i;
    output  ahbl_hreadyout_o;
    output  ahbl_hresp_o;
    input  ahbl_hsel_i;
    input  ahbl_hwrite_i;
    input  clk_i;
    input  resetn_i;
endmodule