/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2025.1.0.2506031608
    Soft IP Version: 1.0.0
    2025 09 01 18:08:32
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module system0 (HCLK, HRESETn, HADDR, HBURST, HTRANS, HSIZE, HWRITE, HSEL,
    HREADY, HWDATA, HRDATA, HREADYOUT, HRESP, sram_addr, sram_we, sram_maskwe,
    sram_re, sram_din, sram_dout, sram_write_done, sram_read_valid)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  HCLK;
    input  HRESETn;
    input  [31:0]  HADDR;
    input  [2:0]  HBURST;
    input  [1:0]  HTRANS;
    input  [2:0]  HSIZE;
    input  HWRITE;
    input  HSEL;
    input  HREADY;
    input  [31:0]  HWDATA;
    output  [31:0]  HRDATA;
    output  HREADYOUT;
    output  HRESP;
    output  [13:0]  sram_addr;
    output  sram_we;
    output  [3:0]  sram_maskwe;
    output  sram_re;
    output  [31:0]  sram_din;
    input  [31:0]  sram_dout;
    input  sram_write_done;
    input  sram_read_valid;
endmodule