    timer __(.int_o( ),
        .ahbl_haddr_i( ),
        .ahbl_hburst_i( ),
        .ahbl_hrdata_o( ),
        .ahbl_hsize_i( ),
        .ahbl_htrans_i( ),
        .ahbl_hwdata_i( ),
        .ahbl_hready_i( ),
        .ahbl_hreadyout_o( ),
        .ahbl_hresp_o( ),
        .ahbl_hsel_i( ),
        .ahbl_hwrite_i( ),
        .systime_o( ),
        .clk_i( ),
        .resetn_i( ));
