--  >>>>>>>>>>>>>>>>>>>>>>> COPYRIGHT NOTICE <<<<<<<<<<<<<<<<<<<<<<<<<
--	  ------------------------------------------------------------------
--	  Copyright(c) 2019 - 2025 by Lattice Semiconductor Corporation
--      ALL RIGHTS RESERVED
--	  ------------------------------------------------------------------

--	  IMPORTANT: THIS FILE IS USED BY OR GENERATED BY the LATTICE PROPEL™
--DEVELOPMENT SUITE, WHICH INCLUDES PROPEL BUILDER AND PROPEL SDK.

--	   Lattice grants permission to use this code pursuant to the
--       terms of the Lattice Propel License Agreement.

--     DISCLAIMER :

--       LATTICE MAKES NO WARRANTIES ON THIS FILE OR ITS CONTENTS, WHETHER
--EXPRESSED, IMPLIED, STATUTORY, OR IN ANY PROVISION OF THE LATTICE PROPEL
--LICENSE AGREEMENT OR COMMUNICATION WITH LICENSEE, AND LATTICE SPECIFICALLY
--DISCLAIMS ANY IMPLIED WARRANTY OF MERCHANTABILITY OR FITNESS FOR A
--PARTICULAR PURPOSE.LATTICE DOES NOT WARRANT THAT THE FUNCTIONS CONTAINED
--HEREIN WILL MEET LICENSEE'S REQUIREMENTS, OR THAT LICENSEE'S OPERATION OF
--ANY DEVICE, SOFTWARE OR SYSTEM USING THIS FILE OR ITS CONTENTS WILL BE
--UNINTERRUPTED OR ERROR FREE, OR THAT DEFECTS HEREIN WILL BE CORRECTED.
--LICENSEE ASSUMES RESPONSIBILITY FOR SELECTION OF MATERIALS TO ACHIEVE ITS
--INTENDED RESULTS, AND FOR THE PROPER INSTALLATION, USE, AND RESULTS 
--OBTAINED THEREFROM.LICENSEE ASSUMES THE ENTIRE RISK OF THE FILE AND ITS 
--CONTENTS PROVING DEFECTIVE OR FAILING TO PERFORM PROPERLY AND IN SUCH 
--EVENT, LICENSEE SHALL ASSUME THE ENTIRE COST AND RISK OF ANY REPAIR, 
--SERVICE, CORRECTION, OR ANY OTHER LIABILITIES OR DAMAGES CAUSED BY OR 
--ASSOCIATED WITH THE SOFTWARE.IN NO EVENT SHALL LATTICE BE LIABLE TO ANY 
--PARTY FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, 
--INCLUDING LOST PROFITS, ARISING OUT OF THE USE OF THIS FILE OR ITS 
--CONTENTS, EVEN IF LATTICE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH 
--DAMAGES.LATTICE'S SOLE LIABILITY, AND LICENSEE'S SOLE REMEDY, IS SET FORTH 
--ABOVE.LATTICE DOES NOT WARRANT OR REPRESENT THAT THIS FILE, ITS CONTENTS 
--OR USE THEREOF DOES NOT INFRINGE ON THIRD PARTIES' INTELLECTUAL PROPERTY 
--RIGHTS, INCLUDING ANY PATENT. IT IS THE USER'S RESPONSIBILITY TO VERIFY THE 
--USER SOFTWARE DESIGN FOR CONSISTENCY AND FUNCTIONALITY THROUGH THE USE OF 
--FORMAL SOFTWARE VALIDATION METHODS.

--     ------------------------------------------------------------------

--VHDL instantiation template

component ice40_sm is
    port (sram_dout: in std_logic_vector(31 downto 0);
        ip_int_i: in std_logic_vector(1 downto 0);
        ip_rdata_i: in std_logic_vector(7 downto 0);
        sram_addr: out std_logic_vector(31 downto 0);
        sram_din: out std_logic_vector(31 downto 0);
        sram_maskwe: out std_logic_vector(3 downto 0);
        ip_addr_o: out std_logic_vector(7 downto 0);
        ip_wdata_o: out std_logic_vector(7 downto 0);
        gpio_io: inout std_logic_vector(7 downto 0);
        clk_i: in std_logic;
        rstn_i: in std_logic;
        sram_read_valid: in std_logic;
        sram_write_done: in std_logic;
        rxd: in std_logic;
        sram_re: out std_logic;
        sram_we: out std_logic;
        ip_stb_o: out std_logic;
        ip_we_o: out std_logic;
        txd: out std_logic;
        ip_ack_i: in std_logic
    );
    
end component ice40_sm;
_inst: ice40_sm port map (gpio_io => __,
                          ip_int_i => __,
                          ip_rdata_i => __,
                          ip_addr_o => __,
                          ip_wdata_o => __,
                          ip_stb_o => __,
                          ip_we_o => __,
                          ip_ack_i => __,
                          sram_dout => __,
                          sram_addr => __,
                          sram_din => __,
                          sram_maskwe => __,
                          sram_read_valid => __,
                          sram_write_done => __,
                          sram_re => __,
                          sram_we => __,
                          rxd => __,
                          txd => __,
                          clk_i => __,
                          rstn_i => __);
                          