/*   ==================================================================
 
     >>>>>>>>>>>>>>>>>>>>>>> COPYRIGHT NOTICE <<<<<<<<<<<<<<<<<<<<<<<<<
     ------------------------------------------------------------------
     Copyright (c) 2019-2025 by Lattice Semiconductor Corporation
     ALL RIGHTS RESERVED
     ------------------------------------------------------------------
 
       IMPORTANT: THIS FILE IS USED BY OR GENERATED BY the LATTICE PROPEL
       DEVELOPMENT SUITE, WHICH INCLUDES PROPEL BUILDER AND PROPEL SDK.
 
       Lattice grants permission to use this code pursuant to the
       terms of the Lattice Propel License Agreement.
 
     DISCLAIMER:
 
    LATTICE MAKES NO WARRANTIES ON THIS FILE OR ITS CONTENTS,
    WHETHER EXPRESSED, IMPLIED, STATUTORY,
    OR IN ANY PROVISION OF THE LATTICE PROPEL LICENSE AGREEMENT OR
    COMMUNICATION WITH LICENSEE,
    AND LATTICE SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTY OF
    MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.
    LATTICE DOES NOT WARRANT THAT THE FUNCTIONS CONTAINED HEREIN WILL MEET
    LICENSEE 'S REQUIREMENTS, OR THAT LICENSEE' S OPERATION OF ANY DEVICE,
    SOFTWARE OR SYSTEM USING THIS FILE OR ITS CONTENTS WILL BE
    UNINTERRUPTED OR ERROR FREE,
    OR THAT DEFECTS HEREIN WILL BE CORRECTED.
    LICENSEE ASSUMES RESPONSIBILITY FOR SELECTION OF MATERIALS TO ACHIEVE
    ITS INTENDED RESULTS, AND FOR THE PROPER INSTALLATION, USE,
    AND RESULTS OBTAINED THEREFROM.
    LICENSEE ASSUMES THE ENTIRE RISK OF THE FILE AND ITS CONTENTS PROVING
    DEFECTIVE OR FAILING TO PERFORM PROPERLY AND IN SUCH EVENT,
    LICENSEE SHALL ASSUME THE ENTIRE COST AND RISK OF ANY REPAIR, SERVICE,
    CORRECTION,
    OR ANY OTHER LIABILITIES OR DAMAGES CAUSED BY OR ASSOCIATED WITH THE
    SOFTWARE.IN NO EVENT SHALL LATTICE BE LIABLE TO ANY PARTY FOR DIRECT,
    INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES,
    INCLUDING LOST PROFITS,
    ARISING OUT OF THE USE OF THIS FILE OR ITS CONTENTS,
    EVEN IF LATTICE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
    LATTICE 'S SOLE LIABILITY, AND LICENSEE' S SOLE REMEDY,
    IS SET FORTH ABOVE.
    LATTICE DOES NOT WARRANT OR REPRESENT THAT THIS FILE,
    ITS CONTENTS OR USE THEREOF DOES NOT INFRINGE ON THIRD PARTIES'
    INTELLECTUAL PROPERTY RIGHTS, INCLUDING ANY PATENT. IT IS THE USER' S
    RESPONSIBILITY TO VERIFY THE USER SOFTWARE DESIGN FOR CONSISTENCY AND
    FUNCTIONALITY THROUGH THE USE OF FORMAL SOFTWARE VALIDATION METHODS.
     ------------------------------------------------------------------
 
     ================================================================== */
 
#ifndef SYS_PLATFORM_H
#define SYS_PLATFORM_H

#include <riscv_errors.h>
/* general info */
#define DEVICE_FAMILY "iCE40UP"
#define iCE40UP5K

/* ip instance base address */

#define CPU_INST_NAME "cpu_inst"
#define CPU_INST_BASE_ADDR 0xffff0000

#define GPIO_INST_NAME "gpio_inst"
#define GPIO_INST_BASE_ADDR 0x40000

#define ICE40_IP_IF_INST_NAME "ice40_ip_if_inst"
#define ICE40_IP_IF_INST_BASE_ADDR 0x50000

#define SYSTEM0_INST_NAME "system0_inst"
#define SYSTEM0_INST_BASE_ADDR 0x0

#define SYSTEM1_INST_NAME "system1_inst"
#define SYSTEM1_INST_BASE_ADDR 0x20000

#define TIMER_INST_NAME "timer_inst"
#define TIMER_INST_BASE_ADDR 0x60000

#define UART_INST_NAME "uart_inst"
#define UART_INST_BASE_ADDR 0x70000

/* ip instance rename */
#define RISCV_SM_INST_0 CPU_INST
#define GPIO_AHB_INST_0 GPIO_INST
#define ICE40_IP_IF_AHB_INST_0 ICE40_IP_IF_INST
#define SPSRAM_IF_AHB_SM_INST_0 SYSTEM0_INST
#define SPSRAM_IF_AHB_SM_INST_1 SYSTEM1_INST
#define TIMER_AHB_INST_0 TIMER_INST
#define UART_AHB_INST_0 UART_INST

/* register test (reg_test.c) is to test the accessibility of the design by accessing the 
testable register of each IP instance, it might affect the environment during test. 
Treat this with care, it's expected to be done only once when the SOC is generated on fly, 
and make sure to disable it when developing the application firmware. */
#define REG_TEST_ENABLE 0

/* cpu_inst parameters */
#define CPU_INST_DEBUG_ENABLE False
#define CPU_INST_DEVICE iCE40UP
#define CPU_INST_E_EXT False
#define CPU_INST_E_STANDALONE False
#define CPU_INST_HB_RANGE 1
#define CPU_INST_HW_WATCHPOINT 0
#define CPU_INST_IRQ_NUM 2
#define CPU_INST_JTAG_CHANNEL 14
#define CPU_INST_PICTIMER_START_ADDR 0xFFFF0000
#define CPU_INST_PIC_ENABLE True
#define CPU_INST_RESET_VECTOR 0x00000000
#define CPU_INST_RESET_VECTOR_INPUT 00000000
#define CPU_INST_SIMULATION False
#define CPU_INST_SOFT_JTAG False
#define CPU_INST_TIMER_ENABLE False

/* gpio_inst parameters */
#define GPIO_INST_BUS_WIDTH 8
#define GPIO_INST_DEVICE ICE40UP
#define GPIO_INST_DIRECTION 0xFF
#define GPIO_INST_INIT_OUTVAL 0x00

/* ice40_ip_if_inst parameters */

/* system0_inst parameters */

/* system1_inst parameters */

/* timer_inst parameters */
#define TIMER_INST_PRESCALE 11
#define TIMER_INST_USE_DSP 1

/* uart_inst parameters */
#define UART_INST_BUFFER_SIZE 512
#define UART_INST_CLOCK_FREQ 12000000
#define UART_INST_UART_BAUDRATE 115200

/* interrupt */

#define ICE40_IP_IF_INST_IRQ 0
#define TIMER_INST_IRQ 0
#define UART_INST_IRQ 1

#endif
