/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2025.1.0.2506031608
    Soft IP Version: 1.0.0
    2025 09 02 15:04:48
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module ice40_ip_if (clk, resetn, int_o, HADDR, HBURST, HTRANS, HSIZE, HWRITE,
    HSEL, HREADY, HWDATA, HRDATA, HREADYOUT, HRESP, ip_addr_o, ip_wdata_o,
    ip_rdata_i, ip_we_o, ip_stb_o, ip_int_i, ip_ack_i)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clk;
    input  resetn;
    output  int_o;
    input  [31:0]  HADDR;
    input  [2:0]  HBURST;
    input  [1:0]  HTRANS;
    input  [2:0]  HSIZE;
    input  HWRITE;
    input  HSEL;
    input  HREADY;
    input  [31:0]  HWDATA;
    output  [31:0]  HRDATA;
    output  HREADYOUT;
    output  HRESP;
    output  [7:0]  ip_addr_o;
    output  [7:0]  ip_wdata_o;
    input  [7:0]  ip_rdata_i;
    output  ip_we_o;
    output  ip_stb_o;
    input  [1:0]  ip_int_i;
    input  ip_ack_i;
endmodule